@ 16:23:27 ➜ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "house-price-predict-pod" already exists
NAME                      READY   STATUS    RESTARTS   AGE
house-price-predict-pod   1/1     Running   0          5m48s
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080

@ 16:26:12 ➜ kubectl logs house-price-predict-pod
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 551-691-049
[2021-01-06 15:24:19,036] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-01-06 15:24:19,047] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-01-06 15:24:19,055] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-01-06 15:24:19,059] INFO in app: Prediction:
[20.35373177134412]
127.0.0.1 - - [06/Jan/2021 15:24:19] "POST /predict HTTP/1.1" 200 -
